import Header from "@/components/Header";
import "./globals.scss";
import { Footer } from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { CartProvider } from "@/context/CartContext";

export const metadata = {
  title: "Almacén Paykuna | Almacén Orgánico",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Asegúrate de que esté en `public/`
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header></Header>
          <main>
            {children}
            <ToastContainer position="top-center" autoClose={1500} />
          </main>
          <Footer></Footer>
        </CartProvider>
      </body>
    </html>
  );
}
