import Header from "@/components/Header";
import "./globals.scss";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Almacén Paykuna | Almacén Orgánico",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Asegúrate de que esté en `public/`
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <main>
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
