import Header from "@/components/Header";
import "./globals.scss";
import { Footer } from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Almacén Paykuna | Almacén Orgánico",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Asegúrate de que esté en `public/`
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <main>
          {children}
          <ToastContainer position="top-right" autoClose={1500} />
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
